{{- if eq .Values.kind "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "bluenet.name" . }}
  labels:
    {{- include "bluenet.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- with .Values.cronjob.timeZone }}
  timeZone: {{ . }}
  {{- end }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "bluenet.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- include "bluenet.podSpec" . | nindent 10 }}
{{- end }}
